sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t omsquare/zephyr-sdk .
  - docker push omsquare/zephyr-sdk
